### ISSUE TITLE
Travel-restriction

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#197]
Rebalance: #192 

## Stage 1: teleport-hooks in mods
* [x] https://github.com/pandorabox-io/telemosaic
* [x] https://github.com/Sokomine/travelnet
* [ ] ~~/tpr /tphr (mod-source?)~~
* [x] http://github.com/thomasrudin-mt/missions (teleport-wand: missions.can_create_wand)
* [x] sethome (default and unified inv)
* [x] globalstep coord-checker
* [ ] jumpdrive? (exploit: everbody can take a ride with someones spaceship)

## Stage 2: limiting formula
Height above y=0 limited:
* linear?
* fixed steps?

**Comment by thomasrudin** [comment]
```lua
	local req_xp = 0

	if pos.y > 5000 then
		-- moon
		req_xp = 10000
	end

	if pos.y > 6000 then
		-- asteroids
		req_xp = 20000
	end

	if pos.y > 10000 then
		-- mars
		req_xp = 50000
	end

	if pos.y > 17000 then
		-- warzone
		req_xp = 100000
	end

```
