### ISSUE TITLE
Map purge (unprotected areas)

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#349]
Project (wip): 
* ~~https://github.com/thomasrudin-mt/mtpurge~~
* https://github.com/thomasrudin-mt/mapcleaner

## Current DB-State
* 50 GB Blocks
* ~~77~~ 90+ million mapblocks
* Primary index on `blocks` of 10+ GB

## Preparations
* [x] Redesign moon, mars and space mapgen _before_ the purge
* [x] Define "protected" areas (https://github.com/thomasrudin-mt/mtpurge/issues/1)
* [x] Safety range: 16*5 blocks (80 blocks) around protected areas
* [x] protect `Tagada`'s streets with xp-protectors (https://pandorabox.io/map/#!/map/0/10/-11303/360)

## Optional stuff
* [ ] New mapgen stuff? (~~maybe the whole `cool_trees` mod?~~)
* [ ] ~~Mapgen xp-penalty? (should prevent exploring a bit, or slow it down)~~ (not sure about that anymore)

## Follow-up steps
* [ ] shorter x/y/z types (https://github.com/minetest/minetest/pull/9108)

**Comment by SwissalpS** [comment]
some concerns have come up whether xp-protectors also count as protected areas.

**Comment by thomasrudin** [comment]
> some concerns have come up whether xp-protectors also count as protected areas.

I did add that to my list.
The `mtpurge` project is not yet ready though, and i'm not in a hurry, there is still something above 50 gb free on that disk :smile: 

When it is ready it will remove whole mapchunks ( (16*5)^3 blocks ) but with a safety range of one or multiple chunks itself.

By the way: the blacklist (https://github.com/thomasrudin-mt/mtpurge/issues/1) can be extended with *artificial* nodes (bricks, torches, etc) so that nobody will loose anything...

**Comment by OgelGames** [comment]
> the blacklist ([thomasrudin-mt/mtpurge#1](https://github.com/thomasrudin-mt/mtpurge/issues/1)) can be extended with _artificial_ nodes (bricks, torches, etc) so that nobody will loose anything...

Wouldn't it be easier to do the reverse, and just check if a mapblock only contains mapgen blocks, or is that not possible?

**Comment by thomasrudin** [comment]
> Wouldn't it be easier to do the reverse, and just check if a mapblock only contains mapgen blocks, or is that not possible?

I think the blacklist would be shorter. Honestly, i'm not that sad if some unprotected cobble-shacks get removed ;)

Also: the radius around the blacklist nodes is 80 to 160 blocks (assuming 1 mapchunk safety zone), i think that should be enough.
For example: if you have a protector or travelnet placed the next 80 blocks around that will be preserved.

I'm testing that of course on the test-server first, and give everybody time to see if something is missing.

**Comment by OgelGames** [comment]
I guess it probably would be good enough, but I'm just thinking about new players, those who have been playing for a few days but haven't protected their home yet.
I myself was one of them,

**Comment by OgelGames** [comment]
I guess it probably would be enough, but I'm just thinking about new players, those who have been playing for a few days but haven't protected their home yet, I myself once being one of them.

Something else that came to mind, was dungeons, they can have both chests and torches naturally generated inside...

**Comment by SwissalpS** [comment]
we can hand out prot-stones to newbs when the purge is about to happen.
The dungeons are not a problem imo, they will be regenerated randomly with the newest settings.

**Comment by int-ua** [comment]
Were bones considered to be protected? I'm ready to spend some time preserving items from bones for original owners as I already do, leaving the bones itself for myself as a reward. I only need a list of coordinates, maybe published publicly to speed the process up. I would really enjoy that.

**Comment by thomasrudin** [comment]
> I only need a list of coordinates

## Script

```bash
# task: fetch mapobjects with given type from mapserver
# requirements: jq, curl
curl 'https://pandorabox.io/map/api/mapobjects/' \
 -H 'Content-Type: application/json; charset=utf-8' \
 --data '{"pos1":{"x":-2048,"y":-2048,"z":-2048},"pos2":{"x":2048,"y":2048,"z":2048},"type":"bones"}' \
 | jq
```

## Result
(truncated)

```json
[
  {
    "mapblock": {
      "x": -1671,
      "y": 0,
      "z": -82
    },
    "x": -26729,
    "y": 1,
    "z": -1306,
    "type": "bones",
    "mtime": 1554099532,
    "attributes": {
      "owner": "Brzezowski58",
      "time": "0"
    }
  },
  {
    "mapblock": {
      "x": 1551,
      "y": 0,
      "z": 512
    },
    "x": 24820,
    "y": 0,
    "z": 8194,
    "type": "bones",
    "mtime": 1558862825,
    "attributes": {
      "owner": "huggy2929",
      "time": "20"
    }
  },
  {
    "mapblock": {
      "x": 594,
      "y": 1,
      "z": -62
    },
    "x": 9512,
    "y": 17,
    "z": -979,
    "type": "bones",
    "mtime": 1562860499,
    "attributes": {
      "owner": "nixnh",
      "time": "0"
    }
  }
]
```

## References

* Bones mapobject: https://github.com/minetest-tools/mapserver/blob/master/mapobject/bones.go
* Others: https://github.com/minetest-tools/mapserver/tree/master/mapobject

Have fun :smile:

Tell me if you have issues executing the query, i can post the results somewhere public if you want, but this is the most "live" data you can get...

**Comment by int-ua** [comment]
Me and jackb cleared all the available ones in the API but I keep finding ones that were not listed in it. I even saw some non-listed near the ones listed. Should I open a new issue?

**Comment by thomasrudin** [comment]
> Me and jackb cleared all the available ones in the API but I keep finding ones that were not listed. I even saw some non-listed near the ones listed. Should I open a new issue?

I experienced that some time ago but could not reproduce it, i opened an issue in the mapserver:
https://github.com/minetest-tools/mapserver/issues/68

**Comment by OgelGames** [comment]
> New mapgen stuff? (maybe the whole `cool_trees` mod?)

I'd say no to that, `cool_trees` includes pinapple, birch, and palms, which we already have. I do kinda like the larch and jacaranda trees just for the additional colors, but even those aren't _really_ needed IMO...

**Comment by int-ua** [comment]
Can bones be left in place with _everything_ around them deleted, no safety range? I'm not yet saying it's worth the trouble, just curious. Although they would've been the uniq rich "ore" to find, a bit more fun. Maybe even turn them into something else. But that's only in case whole mapblock doesn't have to be preserved.

**Comment by thomasrudin** [comment]
> Can bones be left in place with everything around them deleted

That does not work that way, sadly. Its everything or nothing...

> they would've been the uniq rich "ore" to find

Interesting idea, but how do you mitigate `/killme` farming for bones?

**Side note**: i need to rethink my previous work with the `mtpurge` application: i tested it on a backup copy and it would have took several weeks to complete, with all the downtime of course... :disappointed: . I post here if i have further ideas...

**Comment by kiedtl** [comment]
Can you extend the blacklist with train tracks?

**Comment by thomasrudin** [comment]
> Can you extend the blacklist with train tracks?

Will do, yes :+1: https://github.com/thomasrudin-mt/mapcleaner/issues/1

Also: i moved to a pure-lua solution which i'm testing currently on `test.pandorabox.io`:
* Repo: https://github.com/thomasrudin-mt/mapcleaner
* Stats: https://monitoring.minetest.land/d/j5hRG5LZz/mapcleaner?orgId=1&refresh=5s&var-instance=test.pandorabox.io

The lower y-axis below about -40 should have been cleaned there already, if someone wants to check out if their builds still exist :smile: 

(this is not "production" ready yet, don't worry)

I update here if i have news...

**Comment by SwissalpS** [comment]
I payed a very brief visit to my place at bottom of universe, seems to exist :)

**Comment by SwissalpS** [comment]
will new mapgen settings make sulfur less rare on earth or other places? Most of the old moon is probably going to survive the purge but if it didn't, sulfur would become rather rare. I have not found meaningful quantities in earth. Chromium and Zinc might fall into that category too.
Having quarried big parts of new asteroid, I have found sufficient other resources. Only these three seem to be hard to get if old moon should be 'emptied'.

**Comment by thomasrudin** [comment]
> will new mapgen settings make sulfur less rare on earth or other places?

The "new" mapgen (the one thats active now) is full of ores again, sulfur should generate like in the old days :smile: 

> Most of the old moon is probably going to survive the purge

I think most of the moon surface got cleaned up:
https://test.pandorabox.io/map/#!/map/1/5/112/-1008
vs.
https://pandorabox.io/map/#!/map/1/5/112/-1008
<img src="https://i.imgur.com/5HuTUTW.png"></img>

**Comment by thomasrudin** [comment]
closing this, special backup is done (aside from the daily/weekly rotation) in case something unexpected happens...
