### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#419]
Work-in-progress: https://discord.gg/mK6esa4

## TODO
* [x] Ingame chat
* [x] Restrict ingame talk/spam
* [x] Moderation channels
* [x] Other feeds/news
* [ ] Address privacy issues (if any)
* [ ] Bot commands (login, status, etc)
* [x] Publish to `umtd` (unofficial minetest discord)

**Comment by thomasrudin** [comment]
closing this, discord works as expected...
