### ISSUE TITLE
spectator account

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#461]
## TODO

* [ ] disable damage
* [ ] disable stamina
* [ ] teleport (no interact = can't use travelnets/telemosaic)
* [ ] slow movement (player_monoids)
* [ ] xp height restriction

**Comment by OgelGames** [comment]
Related: https://github.com/pandorabox-io/pandorabox.io/issues/333

**Comment by BuckarooBanzay** [comment]
> Related: #333

Totally forgot that one :yum:

**Comment by wsor4035** [comment]
dumping this here https://github.com/greenxenith/spectator

**Comment by BuckarooBanzay** [comment]
> Q: Do you plan to maintain this?
> A: No.

:rofl: 

```lua
minetest.register_privilege("spectator", {
	description = "Allows player to use spectator mode."
})
```

This is good, so we can limit it to established players and not every new player can noclip/fly through everything

Even areas are checked:
```lua
if not areas:canInteract(player:get_pos(), name) then
 spectator.send(name, "You entered another player's area, returning to origin.")
 player:set_pos(data.origin)
end
```

The only issue i have is that if you are leaving a nearby fly beacon you will be essentially "shot down" by the effect-change, but that can be added to that (`beacon`) mod with a `spectator.is_spectator(name)` check...

I added it to the test-server but haven't done any testing there yet :+1:

**Comment by OgelGames** [comment]
> The only issue i have is that if you are leaving a nearby fly beacon you will be essentially "shot down" by the effect-change

And not being able to spectate on the moon or mars, and whatever other issues that would result from privs being overridden... :/

**Comment by BuckarooBanzay** [comment]
> And not being able to spectate on the moon or mars, and whatever other issues that would result from privs being overridden... :/

Hm, true but i still think it might be possible to integrate that mod: i updated the tasks/todo notes accordingly..

**Comment by SwissalpS** [comment]
Another mod that takes slightly different approach: https://github.com/minetest-mods/spectator_mode

I have not tested how it works on the pandorabox set of mods with xp restricted areas.
IMO a visitor should be allowed to visit mars as observer of an advanced player.

It can be configured to allow only players with certain priv to use and the privs while observing can be tweaked too.
(i.e. interact is revoked by default, noclip can be granted temporarily)

**Comment by S-S-X** [comment]
> Another mod that takes slightly different approach: https://github.com/minetest-mods/spectator_mode

Noticed that there is some privilege config for different watcher levels.
For some administrative purposes watching would be useful but would be better to not inform player immediately.
However it would still be nice to always directly inform player who is being watched.

Would it be good to always inform player when watcher is detached without looking at privileges?

Maybe there's situations where mentioning it is not very useful or good thing to do but then also allowing privileged players to watch other players without ever informing them also does not sound exactly nice.
Got any opinions / ideas of possible situations where one or other would be better way to go?

Also I'm not 100% sure how it exactly works currently but assumed that watching is only logged but no chat messages sent if watcher has direct watching privs.
