### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by BuckarooBanzay** [pandorabox-io/pandorabox.io#528]
Various maintenance tasks

## Auth db migration
<details>

* [x] migrate auth-db to postgres for cleanup and maintenance

**world.mt**
```diff
+pgsql_auth_connection = host=postgres port=5432 user=postgres password=enter dbname=postgres
```

**script**
```bash
# host
docker-compose stop minetest
docker-compose run minetest /bin/bash
# container
time minetestserver --world /data/world --config /data/minetest.conf --migrate-auth postgresql
# Successfully migrated 109611 auth entries
# real	0m44.048s
exit
# host
docker-compose start minetest
```
</details>

## Auth db cleanup
<details>

pseudocode: `remove player where xp < 100 and last-login > 1 month`

* [x] `player` cleanup
```sql
delete from player
 where name in (
  select name
  from player p
  join player_metadata pm on p.name = pm.player
  where pm.attr = 'xp' and pm.value::int < 100
  and modification_date < date '2020-07-01'
);
-- NOTE: takes a couple seconds: potential lockup!
```

* [x] `auth` cleanup
```sql
delete from auth where name not in (select name from player);
```

</details>

## Mapcleaner
<details>
* [x] live-cleanup 3 to 4 days (Status: https://pandorabox.io/mapcleaner/api/state)

```yml
 mapcleaner:
  image: buckaroobanzay/mapcleaner
  volumes:
   - "./data/minetest/world/areas.dat:/areas.dat"
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: postgres
   PGPASSWORD: enter
   PGPORT: 5432
   AREAS_FILE: /areas.dat
  restart: "no"
```

* Mapblocks
  * old: 127M
  * new: 26M
* Database-size
  * old: 70G
  * new: 18G (gzipped sql-dump: 9G)
</details>

## Large scale removals

<details>
* [x] Amun-system (mod-cleanup: https://github.com/pandorabox-io/pandorabox_custom/pull/26)

```sql
delete from blocks where (posx,posy,posz) in (
	select posx,posy,posz from blocks
	where posx >= 586 and posx <= 663
	and posy >= 590 and posy <= 622
	and posz >= 893 and posz <= 981
	limit 10000
);
```

```
/remove_area 1431
```
</details>

## DB pos fields change

* [x] shrink pos field types
downtime: 15m+

```sql
alter table blocks alter posx type smallint;
alter table blocks alter posy type smallint;
alter table blocks alter posz type smallint;
```

## DB Migration
* [x] from pg 11 to 13
downtime: an hour

```bash
# dump (17m)
docker exec -i testpandoraboxio_postgres_1 pg_dumpall -U postgres | pv | gzip > dump.sql.gz
# stop
docker-compose down
# TODO: rm data/postgres
# upgrade docker-compose.yml
# start
docker-compose up -d postgres
# insert dump (8m)
cat dump.sql.gz | gunzip | docker exec -i testpandoraboxio_postgres_1 psql -U postgres
```

```diff
+  image: postgres:13.1-alpine
```

## Web-map regeneration
* [x] Remove tiles-directory, poi-database and restart mapserver

## IPv6 Docker stack
* [ ] TBD

**Comment by S-S-X** [comment]
Is tagada road / route 66 already protected well enough? At least last time I checked there was large portions of it unprotected.

**Comment by BuckarooBanzay** [comment]
> Is tagada road / route 66 already protected well enough? At least last time I checked there was large portions of it unprotected.
> edit. but cannot directly see priv or xp protectors so no idea if those might be below the road.

I placed a bunch of xp protectors a while back (don't know the exact value anymore but it was pretty low)
There are a few gaps left though, looks like i missed a few chunks:
* [ ] https://test.pandorabox.io/map/#!/map/0/10/-6830/1053
* [ ] https://test.pandorabox.io/map/#!/map/0/9/-10792/-44
* [ ] https://test.pandorabox.io/map/#!/map/0/9/-15599/-105
* [ ] https://test.pandorabox.io/map/#!/map/0/10/-21098/1378

i'll do that before i start the cleanup process on the main server, but if you want to protect it feel free :wink:

**Comment by SwissalpS** [comment]
In the server news you say not to ask, but I have to make sure if the mese lights refer to the mese lights that can be found in mars or the mese light posts that line Tagada's road?

**Comment by BuckarooBanzay** [comment]
> In the server news you say not to ask, but I have to make sure if the mese lights refer to the mese lights that can be found in mars or the mese light posts that line Tagada's road?

I meant the `default:mese_post_light` sorry for the confusion, it was the itemstring i asked from you that is used for Tagada's road.

**Comment by BuckarooBanzay** [comment]
fyi: the mapcleaner is now around mapchunk-y **-12** and moving upwards (everything below -960 should be cleaned up already)

```
mapcleaner_1         | removing chunk { x: 86, y: -12, z: 30 }
mapcleaner_1         | removing chunk { x: 86, y: -12, z: 125 }
mapcleaner_1         | removing chunk { x: 87, y: -12, z: -13 }
mapcleaner_1         | removing chunk { x: 87, y: -12, z: -12 }
mapcleaner_1         | removing chunk { x: 87, y: -12, z: -11 }
mapcleaner_1         | Reading areas from '/areas.dat'
mapcleaner_1         | Registered 10028 areas
mapcleaner_1         | Area protected chunks: 239870
mapcleaner_1         | removing chunk { x: 87, y: -12, z: -10 }
mapcleaner_1         | removing chunk { x: 87, y: -12, z: 7 }
mapcleaner_1         | removing chunk { x: 87, y: -12, z: 8 }
mapcleaner_1         | removing chunk { x: 87, y: -12, z: 9 }
mapcleaner_1         | removing chunk { x: 88, y: -12, z: -13 }
mapcleaner_1         | removing chunk { x: 88, y: -12, z: -12 }
mapcleaner_1         | removing chunk { x: 88, y: -12, z: -11 }
mapcleaner_1         | removing chunk { x: 88, y: -12, z: -10 }
mapcleaner_1         | removing chunk { x: 88, y: -12, z: 6 }
mapcleaner_1         | removing chunk { x: 88, y: -12, z: 7 }
mapcleaner_1         | removing chunk { x: 88, y: -12, z: 9 }
mapcleaner_1         | removing chunk { x: 89, y: -12, z: -13 }
mapcleaner_1         | removing chunk { x: 89, y: -12, z: -12 }
mapcleaner_1         | removing chunk { x: 89, y: -12, z: -11 }
```

**Comment by OgelGames** [comment]
Thought I should note, the wiki page for Amun will also need to be edited or removed after it is removed from the map: https://pandorabox.io/index.php/Amun_system 😉

**Comment by S-S-X** [comment]
> Thought I should note, the wiki page for Amun will also need to be edited or removed after it is removed from the map: https://pandorabox.io/index.php/Amun_system 😉

Edit and add what happened to keep interesting history
